"""Extensible keyword / pattern knowledge base for deterministic intent classification.

Add patterns here (or extend via INTENT_KB_EXTRA JSON env later). Weights are relative;
higher = stronger signal. Multi-word phrases score higher than single tokens.
"""
from __future__ import annotations

from typing import Dict, List, Tuple

# (pattern, weight) — pattern matched as whole word / phrase in normalized text
Pattern = Tuple[str, float]

INTENT_PATTERNS: Dict[str, List[Pattern]] = {
    "study": [
        ("studiare", 3.5),
        ("studio", 2.2),
        ("esame", 3.8),
        ("esami", 3.5),
        ("preparare l'esame", 4.5),
        ("preparare esame", 4.5),
        ("preparazione esame", 4.2),
        ("ripasso", 3.0),
        ("ripassare", 3.2),
        ("università", 2.5),
        ("universita", 2.5),
        ("uni ", 1.5),
        ("appunti", 2.0),
        ("slide", 1.5),
        ("flashcard", 2.5),
        ("quiz", 1.8),
        ("tesi", 2.5),
        ("laurea", 2.0),
        ("compito", 1.2),
        ("compiti", 1.2),
        ("lezione", 1.8),
        ("lezioni", 1.8),
        ("materie", 1.5),
        ("materia", 1.4),
        ("libri di testo", 2.5),
        ("sbobine", 2.5),
        ("oral", 1.2),
        ("orale", 1.5),
        ("scrivere", 0.6),
        ("imparare", 1.8),
        ("formazione", 1.2),
        ("corso di studi", 2.0),
        ("sessione d'esame", 4.0),
        ("sessione di esame", 4.0),
    ],
    "travel": [
        ("vacanza", 4.0),
        ("vacanze", 3.8),
        ("viaggio", 3.5),
        ("viaggiare", 3.5),
        ("volare", 2.5),
        ("volo", 2.8),
        ("aereo", 2.5),
        ("treno", 2.0),
        ("in auto", 3.2),
        ("in macchina", 3.2),
        ("in aereo", 3.0),
        ("in treno", 3.0),
        ("vado a", 3.8),
        ("vado in", 3.6),
        ("andiamo a", 3.6),
        ("hotel", 2.5),
        ("albergo", 2.2),
        ("prenotare viaggio", 4.0),
        # Natural departure phrases (Conversation Engine entry)
        ("parto", 3.6),
        ("partire", 3.4),
        ("parto per", 4.0),
        ("parto a", 3.8),
        ("due settimane parto", 4.2),
        ("partenza", 1.5),
        ("destinazione", 2.0),
        ("bagaglio", 2.0),
        ("passaporto", 2.5),
        ("visto", 1.5),
        ("ferry", 1.8),
        ("traghetto", 2.0),
        ("weekend fuori", 2.5),
        ("weekend", 2.2),
        ("ferie", 3.5),
        ("gita", 2.0),
        ("tour", 1.5),
        ("airbnb", 2.5),
        ("check-in", 1.5),
        ("check in", 1.5),
    ],
    "event": [
        ("biglietto", 4.2),
        ("biglietti", 4.0),
        ("concerto", 4.0),
        ("spettacolo", 3.2),
        ("teatro", 3.0),
        ("stadium", 2.0),
        ("stadio", 2.8),
        ("partita", 2.8),
        ("festival", 3.5),
        ("mostra", 2.0),
        ("evento", 2.5),
        ("serata", 1.8),
        ("cena fuori", 2.0),
        ("aperitivo", 1.8),
        ("compleanno", 2.2),
        ("matrimonio", 2.5),
        ("festa di laurea", 4.5),
        ("feste", 1.5),
        ("festa", 2.2),
        ("cinema", 2.5),
        ("film al cinema", 3.0),
        ("ingresso", 2.0),
        ("ingresso live", 3.0),
        ("ingresso dal vivo", 3.0),
        ("musica live", 3.0),
        ("prenotare tavolo", 2.5),
        ("ingresso", 1.2),
    ],
    "medical": [
        ("visita", 3.0),
        ("dentista", 4.0),
        ("medico", 3.2),
        ("dottore", 3.0),
        ("ospedale", 3.5),
        ("clinica", 2.8),
        ("analisi del sangue", 4.0),
        ("analisi sangue", 3.8),
        ("prenotare visita", 4.0),
        ("controllo medico", 3.8),
        ("fisioterapia", 3.5),
        ("oculista", 3.5),
        ("dermatologo", 3.5),
        ("psicologo", 2.5),  # care: study "psicologia" handled separately
        ("terapia", 2.0),
        ("ricetta", 2.5),
        ("farmacia", 2.0),
        ("pronto soccorso", 3.5),
        ("vaccino", 2.8),
        ("radiografia", 3.0),
        ("ecografia", 3.0),
        ("appuntamento medico", 4.0),
    ],
    "payment": [
        ("fattura", 4.0),
        ("bolletta", 4.2),
        ("bollette", 4.0),
        ("pagare", 3.0),
        ("pagamento", 3.2),
        ("scadenza pagamento", 4.0),
        ("bonifico", 3.5),
        ("rata", 2.5),
        ("rata del mutuo", 4.5),
        ("canone", 2.5),
        ("affitto da pagare", 4.0),
        ("utenze", 3.0),
        ("luce e gas", 3.5),
        ("bolletta luce", 4.2),
        ("bolletta gas", 4.2),
        ("mav", 2.5),
        ("pagoPA", 3.5),
        ("pagopa", 3.5),
        ("f24", 3.0),
        ("tassa", 2.0),
        ("multa", 2.8),
        ("mutuo", 2.8),
    ],
    "financial": [
        ("investimento", 3.5),
        ("budget", 3.0),
        ("risparmi", 2.8),
        ("conto corrente", 3.0),
        ("carta di credito", 2.8),
        ("finanza", 2.5),
        ("dichiarazione dei redditi", 4.0),
        ("730", 2.5),
        ("commercialista", 2.2),
        ("iban", 2.0),
        ("stipendio", 2.0),
        ("spese mensili", 2.8),
    ],
    "administrative": [
        ("documento d'identità", 3.5),
        ("carta d'identità", 3.8),
        ("passaporto da rinnovare", 4.0),
        ("anagrafe", 3.5),
        ("comune", 1.8),
        ("ufficio", 1.2),
        ("pratica", 2.5),
        ("modulo", 2.0),
        ("certificato", 2.5),
        ("autocertificazione", 3.5),
        ("residenza", 2.0),
        ("cambio residenza", 3.5),
        ("patente", 2.5),
        ("rinnovo patente", 3.8),
        ("spid", 2.5),
        ("cie", 2.0),
        ("burocrazia", 3.0),
        ("adempimento", 2.5),
    ],
    "document_review": [
        ("rivedere documento", 4.0),
        ("controllare documento", 3.8),
        ("verificare documento", 3.8),
        ("leggere contratto", 3.5),
        ("contratto da firmare", 4.0),
        ("pdf da leggere", 3.0),
        ("allegato", 1.5),
        ("revisionare", 2.5),
        ("firmare", 2.0),
        ("scansionare", 2.0),
    ],
    "task": [
        ("da fare", 2.0),
        ("todo", 2.5),
        ("task", 2.0),
        ("ricordami di", 2.5),
        ("checklist", 2.5),
        ("sistemare", 1.5),
        ("pulire", 2.0),
        ("ordinare casa", 2.5),
        ("fare la spesa lista", 2.0),
        ("chiamare il", 1.5),
        ("completare", 1.2),
    ],
    "communication": [
        ("rispondere", 3.0),
        ("mandare messaggio", 3.5),
        ("inviare email", 3.8),
        ("scrivere email", 3.5),
        ("whatsapp", 3.0),
        ("chiamare", 2.2),
        ("richiamare", 3.0),
        ("messaggio a", 2.5),
        ("contattare", 2.5),
        ("reply", 2.0),
        ("email da rispondere", 4.0),
    ],
    "shopping": [
        ("comprare", 3.5),
        ("acquistare", 3.5),
        ("shopping", 3.0),
        ("ordine amazon", 3.5),
        ("amazon", 2.0),
        ("fare la spesa", 3.5),
        ("supermercato", 2.8),
        ("negozio", 1.8),
        ("regalo", 2.0),
    ],
    "project": [
        ("progetto", 3.0),
        ("milestone", 2.5),
        ("roadmap", 2.5),
        ("deliverable", 2.5),
        ("lancio", 1.5),
        ("sprint", 2.0),
        ("lavorare al progetto", 3.5),
    ],
    "generic": [
        ("priorità", 0.5),
        ("cosa fare", 0.8),
        ("organizzare", 0.8),
    ],
}

# Subtype rules: if intent wins AND any of these patterns match → subtype
SUBTYPE_RULES: Dict[str, List[Tuple[str, List[Pattern]]]] = {
    "study": [
        ("exam_preparation", [
            ("esame", 2.0),
            ("esami", 2.0),
            ("preparare", 1.0),
            ("preparazione", 1.2),
            ("sessione", 1.0),
            ("orale", 0.8),
        ]),
    ],
    "travel": [
        ("vacation", [
            ("vacanza", 2.0),
            ("vacanze", 2.0),
            ("ferie", 1.5),
        ]),
    ],
    "event": [
        ("concert", [
            ("concerto", 2.0),
            ("biglietto", 1.0),
        ]),
    ],
    "medical": [
        ("appointment", [
            ("visita", 1.5),
            ("appuntamento", 1.5),
        ]),
    ],
    "payment": [
        ("bill", [("bolletta", 2.0), ("bollette", 2.0)]),
        ("invoice", [("fattura", 2.0)]),
    ],
}

# Subject extraction after study/exam cues: "esame di X", "studiare X"
SUBJECT_PATTERNS = [
    r"(?:esame|esami)\s+(?:di|di\s+)?\s*([a-zàèéìòùA-ZÀÈÉÌÒÙ][\wàèéìòù'\-]{2,40})",
    r"studiare\s+(?:l['']|lo\s+|la\s+|il\s+|un\s+|una\s+)?(?:esame\s+(?:di\s+)?)?([a-zàèéìòùA-ZÀÈÉÌÒÙ][\wàèéìòù'\-]{2,40})",
    r"materia\s+([a-zàèéìòùA-ZÀÈÉÌÒÙ][\wàèéìòù'\-]{2,40})",
]

# Source / item_type soft hints (never sole authority; capped)
SOURCE_HINTS: Dict[str, Tuple[str, float]] = {
    "study": ("study", 0.35),
    "quiz_session": ("study", 0.4),
    "event_candidate": ("event", 0.45),
    "google_calendar": ("event", 0.4),
    "internal_calendar": ("event", 0.35),
    "document": ("document_review", 0.25),
    "document_action": ("document_review", 0.25),
}

ITEM_TYPE_HINTS: Dict[str, Tuple[str, float]] = {
    "study": ("study", 0.3),
    "event": ("event", 0.25),
    "travel": ("travel", 0.35),
    "visit": ("medical", 0.4),
    "medical": ("medical", 0.4),
    "bill": ("payment", 0.4),
    "payment": ("payment", 0.4),
    "admin": ("administrative", 0.3),
    "needs_review": ("document_review", 0.25),
    "verify": ("document_review", 0.25),
    "reply": ("communication", 0.35),
    "activity": ("task", 0.15),
    "generic": ("generic", 0.05),
}

# Strong negative: study "psicologia" must not be medical via "psicologo" stem confusion
NEGATIVE_OVERRIDES: List[Tuple[str, str, List[str]]] = [
    # (blocked_intent, if_present, unless_also)
    ("medical", ["psicologia", "esame di psicologia", "studiare"], ["dentista", "medico", "ospedale", "visita medica"]),
]

CLARIFY_LABELS: Dict[str, str] = {
    "study": "Preparare un esame / studiare",
    "event": "Creare / organizzare un evento",
    "travel": "Organizzare un viaggio / vacanza",
    "medical": "Gestire una visita medica",
    "payment": "Pagare una bolletta / fattura",
    "financial": "Gestire qualcosa di finanziario",
    "administrative": "Pratica amministrativa",
    "document_review": "Rivedere un documento",
    "task": "Una cosa da fare",
    "communication": "Rispondere / comunicare",
    "shopping": "Comprare qualcosa",
    "project": "Lavorare a un progetto",
    "generic": "Altro / generico",
}
